#!/usr/bin/env python3
"""
Scan MicroPython source files for MP_QSTR_* references and generate qstrdefs.generated.h.
Usage: python3 generate_qstrdefs.py <micropython_py_dir> <output_path>

Generates QDEF0(MP_QSTR_xxx, 0, 0, "str") entries as expected by qstr.h.
"""

import re
import sys
import os


def decode_mp_qstr(name):
    """Decode MP_QSTR_xxx name back to the original string."""
    if name == "null":
        return ""
    s = name
    # Must do double underscore BEFORE single char replacements
    s = s.replace("__", "_")
    rep = [
        ("_lt_", "<"), ("_gt_", ">"), ("_amp_", "&"), ("_hash_", "#"),
        ("_quot_", '"'), ("_dquot_", '"'), ("_squot_", "'"),
        ("_sol_", "/"), ("_bsol_", "\\"),
        ("_star_", "*"), ("_comma_", ","), ("_plus_", "+"),
        ("_space_", " "), ("_lp_", "("), ("_rp_", ")"),
        ("_lb_", "["), ("_rb_", "]"), ("_lc_", "{"), ("_rc_", "}"),
        ("_percent_", "%"), ("_eq_", "="), ("_dot_", "."),
    ]
    for old, new in rep:
        s = s.replace(old, new)
    return s


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_qstrdefs.py <micropython_py_dir> <output_path>")
        sys.exit(1)

    py_dir = sys.argv[1]
    output_path = sys.argv[2]

    qstrs = set()
    qstrs.add("null")
    qstrs.add("")

    pattern = re.compile(r'MP_QSTR_([a-zA-Z_][a-zA-Z0-9_]*)')

    for root, dirs, files in os.walk(py_dir):
        for f in files:
            if f.endswith('.c') or f.endswith('.h'):
                filepath = os.path.join(root, f)
                try:
                    with open(filepath, 'r', errors='replace') as fh:
                        content = fh.read()
                    matches = pattern.findall(content)
                    for m in matches:
                        qstrs.add(m)
                except Exception as e:
                    print(f"Warning: Error reading {filepath}: {e}", file=sys.stderr)

    output = "// Auto-generated qstrdefs from MicroPython source\n"
    output += "// Generated by scripts/generate_qstrdefs.py\n\n"

    for q in sorted(qstrs):
        decoded = decode_mp_qstr(q)
        escaped = decoded.replace("\\", "\\\\").replace('"', '\\"')
        output += f"QDEF0(MP_QSTR_{q}, 0, 0, \"{escaped}\")\n"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Generated {len(qstrs)} QSTR entries in {output_path}")


if __name__ == '__main__':
    main()