#!/usr/bin/env python3
"""
Scan MicroPython source files for MP_QSTR_* references and generate qstrdefs.generated.h.
Usage: python3 generate_qstrdefs.py <micropython_py_dir> <output_path>
"""

import re
import sys
import os


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_qstrdefs.py <micropython_py_dir> <output_path>")
        sys.exit(1)

    py_dir = sys.argv[1]
    output_path = sys.argv[2]

    qstrs = set()

    # Pattern for MP_QSTR_xxx
    pattern = re.compile(r'MP_QSTR_([a-zA-Z_][a-zA-Z0-9_]*)')

    # Scan py/*.c and py/*.h files
    for root, dirs, files in os.walk(py_dir):
        for f in files:
            if f.endswith('.c') or f.endswith('.h'):
                filepath = os.path.join(root, f)
                try:
                    with open(filepath, 'r', errors='replace') as fh:
                        content = fh.read()
                    matches = pattern.findall(content)
                    for m in matches:
                        qstrs.add(m)
                except Exception as e:
                    print(f"Warning: Error reading {filepath}: {e}", file=sys.stderr)

    # Generate output
    output = "// Auto-generated qstrdefs from MicroPython source\n"
    output += "// Generated by scripts/generate_qstrdefs.py\n\n"
    output += "#ifndef MICROPY_INCLUDED_PY_GENHDR_QSTRDEFS_GENERATED_H\n"
    output += "#define MICROPY_INCLUDED_PY_GENHDR_QSTRDEFS_GENERATED_H\n\n"

    # Sort for reproducibility
    for q in sorted(qstrs):
        output += f"Q({q})\n"

    output += "\n#endif\n"

    # Write output
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Generated {len(qstrs)} QSTR entries in {output_path}")


if __name__ == '__main__':
    main()