#!/usr/bin/env python3
"""
Scan MicroPython source files for MP_QSTR_* references and generate qstrdefs.generated.h.
Usage: python3 generate_qstrdefs.py <micropython_py_dir> <output_path>

Generates QDEF0 entries as expected by qstr.h (included twice in enum).
"""

import re
import sys
import os


def decode_mp_qstr(name):
    """Decode MP_QSTR_xxx name back to the original string."""
    s = name
    s = s.replace("__", "_")
    rep = [
        ("_lt_", "<"), ("_gt_", ">"), ("_amp_", "&"), ("_hash_", "#"),
        ("_quot_", '"'), ("_dquot_", '"'), ("_squot_", "'"),
        ("_sol_", "/"), ("_bsol_", "\\"),
        ("_star_", "*"), ("_comma_", ","), ("_plus_", "+"),
        ("_space_", " "), ("_lp_", "("), ("_rp_", ")"),
        ("_lb_", "["), ("_rb_", "]"), ("_lc_", "{"), ("_rc_", "}"),
        ("_percent_", "%"), ("_eq_", "="), ("_dot_", "."),
    ]
    for old, new in rep:
        s = s.replace(old, new)
    return s


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_qstrdefs.py <micropython_py_dir> <output_path>")
        sys.exit(1)

    py_dir = sys.argv[1]
    output_path = sys.argv[2]

    qstrs = set()

    # QSTRs generated via token-pasting (MP_QSTR_##name) that static scanning cannot find.
    # From MICROPY_PY_ERRNO_LIST in py/mpconfig.h
    errno_list = [
        "EPERM", "ENOENT", "EIO", "EBADF", "EAGAIN", "ENOMEM", "EACCES",
        "EEXIST", "ENODEV", "EISDIR", "EINVAL", "EOPNOTSUPP", "EADDRINUSE",
        "ECONNABORTED", "ECONNRESET", "ENOBUFS", "ENOTCONN", "ETIMEDOUT",
        "ECONNREFUSED", "EHOSTUNREACH", "EALREADY", "EINPROGRESS",
    ]
    for e in errno_list:
        qstrs.add(e)

    # Pattern for MP_QSTR_xxx (with underscore after QSTR)
    pattern = re.compile(r'MP_QSTR_([a-zA-Z_][a-zA-Z0-9_]*)')

    for root, dirs, files in os.walk(py_dir):
        for f in files:
            if f.endswith('.c') or f.endswith('.h'):
                filepath = os.path.join(root, f)
                try:
                    with open(filepath, 'r', errors='replace') as fh:
                        content = fh.read()
                    matches = pattern.findall(content)
                    for m in matches:
                        qstrs.add(m)
                except Exception as e:
                    print(f"Warning: Error reading {filepath}: {e}", file=sys.stderr)

    # Also check for MP_QSTRnull (no underscore - special qstr 0)
    null_pattern = re.compile(r'MP_QSTRnull\b')
    for root, dirs, files in os.walk(py_dir):
        for f in files:
            if f.endswith('.c') or f.endswith('.h'):
                filepath = os.path.join(root, f)
                try:
                    with open(filepath, 'r', errors='replace') as fh:
                        content = fh.read()
                    if null_pattern.search(content):
                        print(f"Note: MP_QSTRnull found in {f}")
                except:
                    pass

    output = "// Auto-generated qstrdefs from MicroPython source\n"
    output += "// Generated by scripts/generate_qstrdefs.py\n\n"

    # First entry: MP_QSTRnull (no underscore) is the special qstr 0
    output += 'QDEF0(MP_QSTRnull, 0, 0, "")\n'

    # Second entry: MP_QSTR_ (empty string) - used in compile.c
    output += 'QDEF0(MP_QSTR_, 0, 0, "")\n'

    # Sort for reproducibility
    for q in sorted(qstrs):
        decoded = decode_mp_qstr(q)
        escaped = decoded.replace("\\", "\\\\").replace('"', '\\"')
        output += f"QDEF0(MP_QSTR_{q}, 0, 0, \"{escaped}\")\n"

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(output)

    print(f"Generated {len(qstrs) + 1} QSTR entries in {output_path}")


if __name__ == '__main__':
    main()